services:
  db:
    image: postgres:17
    ports:
      - 5430:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shortlinker
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
